name: Browser

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    - run: pip install -r web/requirements.txt
    - run: playwright install --with-deps chromium firefox
    - run: python web/test_browser.py
    - run: python web/test_browser.py --browser firefox
